# Creating a array

In [ ]:
import numpy as np
import matplotlib 
a1 = np.array([2,3,4])
print(f"a1 -> {a1}")
a2 = np.array([(2,3,4),(5,6,8)])
print(f"a2 -> {a2}")
a3 = np.array([(2,3,4),(5,6,7)], dtype=complex)
print(f"a3 -> {a3}")
a4 = np.zeros((2,2))
print(f"a4 -> {a4}")
a5 = np.ones((2,2,2))
print(f"a5 -> {a5}")
a6 = np.empty((1,4))
print(f"a6 -> {a6}")
a7 = np.arange(0,100,8)
print(f"a7 -> {a7}")
#When we creating array with arange and float type its
#hard to know how many elements will occur. Thus we have
# linspace function
a8 = np.linspace(0,2,9)
print(f"a8 -> {a8}")

from numpy import pi
x = np.linspace(0, 2*pi,100)
f = np.sin(x)
f

a1 -> [2 3 4]
a2 -> [[2 3 4]
 [5 6 8]]
a3 -> [[2.+0.j 3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j 7.+0.j]]
a4 -> [[0. 0.]
 [0. 0.]]
a5 -> [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
a6 -> [[0. 0. 0. 0.]]
a7 -> [ 0  8 16 24 32 40 48 56 64 72 80 88 96]
a8 -> [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -