# Creating a array

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
a1 = np.array([2,3,4])
print(f"a1 -> {a1}")
a2 = np.array([(2,3,4),(5,6,8)])
print(f"a2 -> {a2}")
a3 = np.array([(2,3,4),(5,6,7)], dtype=complex)
print(f"a3 -> {a3}")
a4 = np.zeros((2,2))
print(f"a4 -> {a4}")
a5 = np.ones((2,2,2))
print(f"a5 -> {a5}")
a6 = np.empty((1,4))
print(f"a6 -> {a6}")
a7 = np.arange(0,100,8)
print(f"a7 -> {a7}")
#When we creating array with arange and float type its
#hard to know how many elements will occur. Thus we have
# linspace function
a8 = np.linspace(0,2,9)
print(f"a8 -> {a8}")

from numpy import pi
x = np.linspace(0, 2*pi,100)
f = np.sin(x)
f

a1 -> [2 3 4]
a2 -> [[2 3 4]
 [5 6 8]]
a3 -> [[2.+0.j 3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j 7.+0.j]]
a4 -> [[0. 0.]
 [0. 0.]]
a5 -> [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
a6 -> [[0. 0. 0. 0.]]
a7 -> [ 0  8 16 24 32 40 48 56 64 72 80 88 96]
a8 -> [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

# Printing Arrays

In [2]:
p1 = np.arange(12).reshape(4,3)
print(p1)
p2 = np.arange(10000).reshape(100,100)
print(p2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# Basic Operations

In [ ]:
b1 = np.array([20,30,40,50])
b2 = np.arange(4)
b3 = b2 - b1
print(b3)
print(b2**2)
print(10 * np.sin(b1))
# product operator is *
# dot product is @ or dot function b1.dot(b2)
# dont mix with the linear algebra topic dot product!
b4 = np.array([[1,1],[0,1]])
b5 = np.array([[2,0],[3,4]])
print(f"elementwise product:\n{b4*b5}")
print(f"matrix product:\n{b4@b5}")
print(f"another way to matrix product:\n{b4.dot(b5)}")

[-20 -29 -38 -47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
elementwise product:
[[2 0]
 [0 4]]
matrix product:
[[5 4]
 [3 4]]
another way to matrix product:
[[5 4]
 [3 4]]


In [10]:
# When operating with arrays of different types, 
# the type of the resulting array corresponds to
# the more general or precise one (a behavior known 
# as upcasting).
b1 = np.ones(3, dtype=np.int32)
b2 = np.linspace(0,pi,3)
print(b2.dtype.name)
b3 = b1 + b2
print(b3)
print(b3.dtype.name)

float64
[1.         2.57079633 4.14159265]
float64


In [26]:
b1 = np.linspace(1,10,10)
print(b1)
print(b1.sum())
print(b1.min())
print(b1.max())
print("-----------------------------")
# if matrix is multidimensional we can apply 
# operations tı specified axis :
b2 = np.arange(12).reshape(3,4)
print(b2)
# axis = 1 is row , axis = 0 is column  
print(b2.sum(axis=1))
print(b2.min(axis=0))
print(b2.max())
print(b2.cumsum(axis=1))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
55.0
1.0
10.0
-----------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[0 1 2 3]
11
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


# Universal Functions

In [27]:
# Math functions such as sin,cos etc. called 
# "universal functions"(ufunc) in numpy.
# outputs are array
u1 = np.arange(3)
print(np.exp(u1))
print(np.sqrt(u1))
u2 = np.array([2., -4., 7])
print(np.add(u1,u2))

[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[ 2. -3.  9.]


# Indexing, slicing and iterating

In [ ]:
s = np.arange(10) ** 2
print(s)
# indexing starts from 0 thus i[2] is third element
print(s[2:5]) # not include i[5] just 2,3,4
s[:6:2] = -5 # 0 to 6 take two step and set -5
print(s)
print(f"reserved =>{s[::-1]}")

[ 0  1  4  9 16 25 36 49 64 81]
[ 4  9 16]
[-5  1 -5  9 -5 25 36 49 64 81]
reserved =>[81 64 49 36 25 -5  9 -5  1 -5]


In [46]:
def f(x,y):
    return 10*x + y # x = i and y = j 

s1 = np.fromfunction(f,(5,4),dtype=int)
print(s1)
print(s1[0:5, 1])
print(s1[:, 3]) 
print(s1[1:3, :])

# When fewer indices are provided than the number of
# axes missing indices are considered complete slices
# [-1] = [-1, :]

print(s1[-2])


[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[ 1 11 21 31 41]
[ 3 13 23 33 43]
[[10 11 12 13]
 [20 21 22 23]]
[30 31 32 33]


In [ ]:
# ... expression
s3 = np.arange(12).reshape(2,2,3)
print(s3)
print("------------------")
print(s3[1,...]) # same as s3[1,:,:]
print("------------------")
print(s3[...,2]) # same as s3[:,:,2]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
------------------
[[ 6  7  8]
 [ 9 10 11]]
------------------
[[ 2  5]
 [ 8 11]]


In [60]:
#iterating
def f(x,y):
    return 10*x + y # x = i and y = j 

s1 = np.fromfunction(f,(5,4),dtype=int)
for row in s1:
    print(row)

for element in s1.flat:
    print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shape manipulation

In [77]:
m = np.arange(12).reshape(3,4)
print(m)
print("----------------------------------------------")
print(m.ravel()) #returns array, flattened
print("----------------------------------------------")
print(m.reshape(6,2))
print("----------------------------------------------")
print(m.T) #transposed
print("----------------------------------------------")
print(f"Transposed shape:{m.T.shape}\nNormal shape:{m.shape}")
print("----------------------------------------------")
print(m) # Notice that m is not changed

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
----------------------------------------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
----------------------------------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
----------------------------------------------
Transposed shape:(4, 3)
Normal shape:(3, 4)
----------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [83]:
m = np.arange(12).reshape(3,4)
print(m)
m.resize((2,6))
print(m)
m = m.reshape((4,-1)) # if we give -1 as parameter, other dimensions will 
# outomatically calculated
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


# Stacking together diffrent arrays

In [ ]:
import numpy as np
st1 = np.arange(4).reshape(2,2)
st2 = np.arange(4,8).reshape(2,2)
print(np.vstack((st1,st2)))#vertical
print(np.hstack((st1,st2)))#horizontal
st3 = np.arange(4).reshape(4,1)
st4 = np.arange(4,8).reshape(4,1)
print(st4)
print(np.column_stack((st3,st4)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[4]
 [5]
 [6]
 [7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [23]:
st5 = np.arange(5).reshape(5,1)
st5[:, np.newaxis]

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]]])

# Splitting one array into several smaller ones

In [31]:
o1 = np.arange(24).reshape(2,12)
#np.hsplit(o1,3)
np.hsplit(o1,(5,7))

[array([[ 0,  1,  2,  3,  4],
        [12, 13, 14, 15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

# Copies and Wiews

In [35]:
#no copy at all
c1 = np.arange(12).reshape(3,4)
c2 = c1
print(c2 is c1)
print(f"c2 id is->{id(c2)} c1 id is->{id(c1)}")
#no object created c2 and c1 same referance

True
c2 id is->2471124523056 c1 id is->2471124523056


In [ ]:
def f(x):
    print(id(x))

print(id(c1))
f(c1)
#Python passes mutable objects as references, so function calls make no copy.


2471124523056
2471124523056


In [ ]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
arr = a.view()
print(arr is a)
print(arr.base is a)
print(arr.flags.owndata) # owndata = The array owns the memory it 
#uses or borrows it from another object.

arr = arr.reshape((2,6))
print(a.shape) # a didnt change
print("-------------------------------------------")
arr[0, 4] = 123
print(a)
print(arr) # when arr changes a will change too.
print("-------------------------------------------")
a[1,3] = -56
print(a) # vice versa
print(arr)

False
True
False
(3, 4)
-------------------------------------------
[[  0   1   2   3]
 [123   5   6   7]
 [  8   9  10  11]]
[[  0   1   2   3 123   5]
 [  6   7   8   9  10  11]]
-------------------------------------------
[[  0   1   2   3]
 [123   5   6 -56]
 [  8   9  10  11]]
[[  0   1   2   3 123   5]
 [  6 -56   8   9  10  11]]
